services:
  - type: web
    name: datasci
    env: python
    region: oregon
    buildCommand: |
      apt-get update
      apt-get install -y chromium-browser
      apt-get install -y libnss3 libatk1.0-0 libatk-bridge2.0-0 libgtk-3-0 libx11-xcb1 libxcb1 libxcomposite1 libxdamage1 libxrandr2 libgbm1 libasound2
      pip install -r requirements.txt
    startCommand: gunicorn app:app

    envVars:
      - key: GOOGLE_CHROME_BIN
        value: /usr/bin/chromium-browser
      - key: CHROME_BIN
        value: /usr/bin/chromium-browser
      - key: CHROMIUM_PATH
        value: /usr/bin/chromium-browser
      - key: KALIEDO_BROWSER
        value: /usr/bin/chromium-browser
